name: COM402 | Advanced Web Design and Development
markdown: redcarpet
highlighter: pygments
permalink: /:title
exclude: ["node_modules", "gulpfile.js", "package.json"]

redcarpet:
  extensions: [strikethrough, tables]

collections:
  resources:
    output: true