name: COM402 | Advanced Web Design and Development
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
permalink: /:title
exclude: ["node_modules", "gulpfile.js", "package.json"]

collections:
  resources:
    output: true